### ISSUE TITLE
option for boxes with corners?

### ISSUE THREAD

**Issue by higgi13425** [bruigtp/flowchart#2]
It would be nice for some journals to have the option for boxes with corners

**Comment by higgi13425** [comment]
Thanks! Very nice!

**Comment by pasahe** [comment]
Hi @higgi13425,

I am not able to change the corner style for the box, as this is a behavior that the package inherits from the {Gmisc} package, which uses this rounded-shape style for the corner.

**Comment by kenkomodo** [comment]
@pasahe I'd also be interested in non-rounded corners as an option in the package.

Would you be able to add this option by setting `box_fn = rectGrob` for `Gmisc::boxGrob()` on the line linked below (instead of using the `Gmisc::boxGrob()` default of `box_fn = roundrectGrob`)?

https://github.com/bruigtp/flowchart/blob/d5254be6ffd9bbb9e3cc66500a0802328b4feb24/R/fc_draw.R#L54

Based on the [`gpar` documentation](https://r-universe.dev/manuals/grid.html#gpar:~:text=%3D%20NULL)-,rectGrob,-(x%20%3D), it seems like a simple edit like this might work?

**Comment by kenkomodo** [comment]
@pasahe I submitted a pull request (https://github.com/bruigtp/flowchart/pull/15) with the update that would make this possible.

**Comment by pasahe** [comment]
Thanks a lot @kenkomodo! I overlooked the fact that there is actually a `box_fn` argument for modifying the rectangle drawing function in the {Gmisc} package. This will be a great enhancement for the package.
